// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnYYq_K3TL9MxyKaCNPkB8SRqAIucF0rI',
    appId: '1:86193565341:web:b9c234bda59b37ee366e74',
    messagingSenderId: '86193565341',
    projectId: 'vanita-lunch-home',
    authDomain: 'vanita-lunch-home.firebaseapp.com',
    storageBucket: 'vanita-lunch-home.firebasestorage.app',
    measurementId: 'G-JJBTY4SKZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8Wdk1E2wXOoHnUPDHq2zeGvh9NlazTrw',
    appId: '1:86193565341:android:fd6281cf57decec0366e74',
    messagingSenderId: '86193565341',
    projectId: 'vanita-lunch-home',
    storageBucket: 'vanita-lunch-home.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpaE_KEtkuVR_pZB4_GkLI8aecOB_zCDY',
    appId: '1:86193565341:ios:1a743c08e63b97cc366e74',
    messagingSenderId: '86193565341',
    projectId: 'vanita-lunch-home',
    storageBucket: 'vanita-lunch-home.firebasestorage.app',
    iosBundleId: 'com.example.adminVlh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpaE_KEtkuVR_pZB4_GkLI8aecOB_zCDY',
    appId: '1:86193565341:ios:1a743c08e63b97cc366e74',
    messagingSenderId: '86193565341',
    projectId: 'vanita-lunch-home',
    storageBucket: 'vanita-lunch-home.firebasestorage.app',
    iosBundleId: 'com.example.adminVlh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnYYq_K3TL9MxyKaCNPkB8SRqAIucF0rI',
    appId: '1:86193565341:web:255fa34ab7d283ca366e74',
    messagingSenderId: '86193565341',
    projectId: 'vanita-lunch-home',
    authDomain: 'vanita-lunch-home.firebaseapp.com',
    storageBucket: 'vanita-lunch-home.firebasestorage.app',
    measurementId: 'G-0CRQRWCDC5',
  );
}
